### ISSUE TITLE
Progress bar is broken for very fast commands

### ISSUE THREAD

**Issue by sharkdp** [tdulcet/Benchmarking-Tool#3]
I guess it happens if there are more than 1000 runs?
![image](https://user-images.githubusercontent.com/4209276/96349582-d2b07400-10b0-11eb-8509-45b32ab0da44.png)

**Comment by tdulcet** [comment]
Thank you for the bug report! Yes, looks like the issue is that the digit grouping on the run number makes the label too long.

**Comment by tdulcet** [comment]
@sharkdp I fixed this in https://github.com/tdulcet/Benchmarking-Tool/commit/1ac1fbbd8a0b85bb9240beb92e1bbb2841409b9b. It should now work for you.

**Comment by sharkdp** [comment]
Thanks!
