### ISSUE TITLE
STDIN is not closed

### ISSUE THREAD

**Issue by sharkdp** [tdulcet/Benchmarking-Tool#4]
Not really a big problem (mostly a curiosity, if you will), but something that I also fixed in hyperfine at some point. Try:

```
bash /tmp/time.sh read
```

**Comment by tdulcet** [comment]
Thank you for the suggestion! This is a very easy change.

**Comment by tdulcet** [comment]
I made the change in https://github.com/tdulcet/Benchmarking-Tool/commit/d6908b6219cc1ec1d3755e693b9034fd24cd9937. The `read` command now produces an error like with hyperfine.

**Comment by sharkdp** [comment]
:+1: Thanks.
